language: csharp
dotnet: 3.1.403
mono: none
solution: WebApi.sln
services: 
  - docker
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test
after_script:
  - heroku container:login
  - docker build . -t hackney-hr-backend -f Dockerfile
  - heroku container:push -a hackney-hr-backend web
  - heroku container:release -a hackney-hr-backend web
  - heroku open