language: csharp
dotnet: 3.1.403
mono: none
solution: WebApi.sln
services: 
  - docker
before_install:
  - docker pull
  - docker run
  - docker ps -a
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test
